#! /usr/bin/env bash

path="$@"

if [[ "$path" == */ ]] ; then
    path=${path::-1}
fi

python3 mergeVideos.py "$path"

if [[ "$path" == '' ]] ; then
    printf "Please specify the path with video files!\nSyntax: mergeVideos.sh path/to/videofiles\n"
    exit
fi

# bash

exit
